server:
  port: 9010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 4
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 16
      connection-test-query: select 1
#    开发
#    url: jdbc:mysql://localhost:3306/chongzhi?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    测试
#    url: jdbc:mysql://43.128.204.64:3306/chongzhi?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: VLHXoqkvS2#3
    #卡密生产
#    url: jdbc:mysql://154.204.34.252:3306/kami?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://10.0.45.5:3306/kami?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #卡密
#    username: kami
#    password: mY3idf6GZykKTMXF

    #手机生产
#    url: jdbc:mysql://154.204.34.252:3306/phoneacct?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://10.0.45.5:3306/phoneacct?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #手机
    username: phoneacct
    password: J4XB5JAzZCshdcsZ

    #手机测试
#    url: jdbc:mysql://154.204.34.252:3306/phonetest?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: phonetest
#    password: 2R5xdbimD2ShG4FT
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  resources:
    static-locations: classpath:/templates  #访问静态页面

